### ISSUE TITLE
Power spectrum must be adapted to FIELD_AXION

### ISSUE THREAD

**Issue by AlexVaq** [veintemillas/jaxions#10]
Currently it only runs for FIELD_SAXION

**Comment by veintemillas** [comment]
With some care it now works. 
Unfoldfield
Scalar::writeMAPTHETA builds an energy density map into the real part of m2 [needed only for axion field] and does other things
powerspectrumUNFOLDED calls energyMap [in SAXION mode, otherwise assumes writeMAPTHETA was called] and works with complex m2
Scalar::thetatom2 copies c_thetha*m + I*c_theta' into complex m2 [works both for PQ and axion]
number power spectrum works with complex m2

**Comment by AlexVaq** [comment]
I'd like to clean this up:
- Remove writeMAPTHETA With the new energy functions one can just call energyMap, and it really doesn't matter whether the field is axion or saxion.
- We need to work out the FFT so it works for all cases and it doesn't involve expensive copying/moving of data.

**Comment by AlexVaq** [comment]
Up this since now we have new functions to analyze the spectrum. They are Saxion ready but have not been tested.

**Comment by AlexVaq** [comment]
Done with the new spectrum, but it won't properly work with saxions.
